Algoritmo "Exercicio 1"
// Descrição   : 1 - Criar um algoritmo e fluxograma que calcule
// o produto de 28 e 43
// Autor(a)    : José Vitor
// Data atual  : 23/02/2021

// Seção de Declarações das variáveis
Var
Resultado : inteiro
Operacao : inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Operacao <-(28 * 43)

Resultado <- Operacao
Escreva("O produto de 28 x 43 é =",Resultado)


Fimalgoritmo