Algoritmo "Exercício 2"
// Disciplina   : Algoritmos
// Descrição   : Criar um algoritmo que imprima a média aritmética
// entre os números 8, 9 e 7
// Autor(a)    : José Vitor
// Data atual  : 23/02/2021
Var
// Seção de Declarações das variáveis 
Media : real
Operacao : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Operacao <-(8 + 9 + 7)/3

Media <- Operacao
Escreva("A média é =",Media)
Fimalgoritmo